# Generated by Django 5.0.6 on 2024-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_purchaseorder_seller_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
